/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PxbScorecard {
        /**
          * The first name
         */
        "firstProp": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPxbScorecardElement extends Components.PxbScorecard, HTMLStencilElement {
    }
    var HTMLPxbScorecardElement: {
        prototype: HTMLPxbScorecardElement;
        new (): HTMLPxbScorecardElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "pxb-scorecard": HTMLPxbScorecardElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PxbScorecard {
        /**
          * The first name
         */
        "firstProp"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "pxb-scorecard": PxbScorecard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "pxb-scorecard": LocalJSX.PxbScorecard & JSXBase.HTMLAttributes<HTMLPxbScorecardElement>;
        }
    }
}
